Explorer/ViewModels/FolderViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Explorer.ViewModels
{
    /*
         At first was idea to use current class for nested folders like:  public IEnumerable<FolderViewModel> NestedFolders { get; set; }
         but AutoMapper does not support recursive projection for current case in EF6 except EF Core (c)(Stack Overflow).
         To solve this problem simplified NestedFolderViewModel was added.
         So AM now works fine and Extension too.
             */
    public class FolderViewModel
    {
        public int Id { get; set; }
        public int ParentId { get; set; }
        public string Name { get; set; }
        public DateTime CreationDate { get; set; }        
        public IEnumerable<NestedFolderViewModel> NestedFolders { get; set; }
    }
}

Explorer/ViewModels/NestedFolderViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Explorer.ViewModels
{
    public class NestedFolderViewModel
    {
        public int Id { get; set; }
        public int ParentId { get; set; }
        public string Name { get; set; }
        public DateTime CreationDate { get; set; }
    }
}

Explorer/Controllers/ExplorerController.cs
using Explorer.Repositories;
using Explorer.Services.Interfaces;
using Explorer.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Explorer.Controllers
{
    public class ExplorerController : AsyncController
    {

        private IFoldersService _foldersService;

        public ExplorerController(IFoldersService foldersService)
        {
            this._foldersService = foldersService;
        }
        // GET: Folders
        public async Task<ActionResult> Index(string path, int? id)
        {
            FolderViewModel rootFolder = null;
            if (path == null)
            {
                rootFolder = await _foldersService.GetRootFolder();
            }
            else
            {
                rootFolder = await _foldersService.GetRootFolderById(id.Value);
            }
            if (rootFolder == null) return new HttpStatusCodeResult(HttpStatusCode.NotFound, "Folder doesn't exist");
            
            return View(rootFolder);
        }
    }
}

Explorer/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Explorer.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult Error()
        {
            return View("Error");
        }
    }
}

Explorer/Views/Explorer/Index.cshtml
@model Explorer.ViewModels.FolderViewModel
@{
    ViewBag.Title = "Folders";
    Uri uri = Request.Url;
    bool isRoot = uri.Segments.Count() == 2;
    string UrlHelper = Server.UrlDecode(uri.Segments.Last());
    bool isFullPath = UrlHelper[UrlHelper.Length - 1] == '/';
    if (!isFullPath)
    {
        UrlHelper += '/';
    }
    string previousUrlHelper2 = "";
    for (int i = 0; i < uri.Segments.Length - 1; i++)
    {
        previousUrlHelper2 += uri.Segments[i];
    }
    if (uri.Segments.Count()>3)
    {
        previousUrlHelper2 = previousUrlHelper2.Remove(previousUrlHelper2.Length - 1, 1) + "?id=" + Model.ParentId;
    }

}



<div class="jumbotron text-center">
    @if (Model.ParentId != 0)
    {
        <a href="@previousUrlHelper2" title="@Model.Name">
            <img src="~/Content/src/up.png" alt="top Logo" align="top" style="width: 30px; height: 30px; border: none" />
        </a>

    }
    <img src="~/Content/src/folder.png" alt="Folder Logo" align="top" style="width: 40px; height: 40px; border: none" />
    @Html.DisplayFor(model => Model.Name)

</div>
@if (Model.NestedFolders.Count() == 0)
{
    <h3 class="text-danger">Folder is empty</h3>
}

<ul class="list-group">
    @{foreach (var nested in Model.NestedFolders)
        {
            string url = "";
            if (isRoot)
            {
                if (!isFullPath)
                {
                    url = string.Format("{0}{1}?id={2}", UrlHelper, nested.Name, nested.Id);
                }
                else
                {
                    url = string.Format("{0}?id={1}", nested.Name, nested.Id);
                }

            }
            else
            {
                url = string.Format("{0}{1}?id={2}", UrlHelper, nested.Name, nested.Id);

            }
            <li class="list-group-item">
                <a href="@url" title="@nested.Name">
                    <h4>
                        <img src="~/Content/src/folder.png" alt="Folder Logo" align="top" style="width: 20px; height: 20px; border: none" />
                        @nested.Name
                    </h4>
                    <span class="badge">@nested.CreationDate.ToString("MM/dd/yyyy ")</span>

                </a>

            </li>
        }
    }
</ul>

Explorer/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Explorer/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Explorer/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET MVC5</h1>
    <p class="lead">File Explorer</p>
    <p><a href="/Explorer/" class="btn btn-primary btn-lg">Explore more &raquo;</a></p>
</div>

Explorer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @*@Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@
                @*@Html.ActionLink("Dynamic folders", "Index", "Explorer", new { area = "" }, new { @class = "navbar-brand" })*@

            </div>
            <div class="navbar-collapse collapse">
                @*<ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>*@
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application for dynamic folders</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>